#!/bin/bash
echo ${1} >> path
echo ${1}
if [ "${1}" == "Philosophy" ]; then
	lines=$(cat path | wc -l)
	lines=$(expr ${lines} - 1)
	echo "${lines} links"
	mv path ./output/
	exit 0
fi

mkdir -p output
wget -nc https://${2-en}.wikipedia.org/wiki/${1} -P ./output &> output/log

filename=$(cat ./output/${1} | ./first_link)
sleep 1
./wikipedia ${filename} ${2}
